### ISSUE TITLE
Docker Image Error

### ISSUE THREAD

**Issue by webmap2015** [klokantech/tileserver-mapnik#11]
I can run docker image, no problem. But, when I web preview, docker stops.

Docker on Windows with Kitematic

![error](https://cloud.githubusercontent.com/assets/10267317/13380486/45f13166-de4d-11e5-9502-8025ec427b00.png)

Docker on Ubuntu 14.04

![error2](https://cloud.githubusercontent.com/assets/10267317/13380967/efacfffa-de57-11e5-82a5-55d45c1e95e4.png)

**Comment by petrsloup** [comment]
Same issue as reported in #10.

@webmap2015 This is fixed now. It should work ok after pulling new docker image.
