### ISSUE TITLE
Error in `node`: double free or corruption (fasttop)

### ISSUE THREAD

**Issue by webmap2015** [klokantech/tileserver-mapnik#15]
At zoom level 6, docker image is stopping. and tile does not exist.

**Comment by klokan** [comment]
Well - this error does not tell anything about your config or data you have used.
How to reproduce the error?
What is the exact error message you see?

**Comment by webmap2015** [comment]
Docker image on Ubuntu 14.04

![error](https://cloud.githubusercontent.com/assets/10267317/14502953/86de98c6-01b6-11e6-895f-994b314b555a.png)

**Comment by klokan** [comment]
We have never met this error on production deployments from v2.0 container.

It looks like a crash in a C++ module (mapnik, etc) - which may be related to your style. If you try the https://github.com/mapbox/mapbox-studio-osm-bright.tm2 style - do you get the same error?

Maybe your hiking-map.tm2 contains some resources causing this issue.

You may try to tweek the version of the modules in package.json dependencies and then provide Pull Request if you manage to solve the problem by correct upgrade.

**Comment by webmap2015** [comment]
ı reinstall Ubuntu and Docker Image, the result not changed

![error](https://cloud.githubusercontent.com/assets/10267317/14581132/d4673f70-03ec-11e6-9ff8-be49424229f6.png)

**Comment by webmap2015** [comment]
I reinstall Ubuntu, Docker Image and try https://github.com/mapbox/mapbox-studio-osm-bright.tm2 style, error is going on. 1-5 and 7-22 zoom level working, but zoom level 6 not working.

And my docker container is after two release than v2.0 container.

![error](https://cloud.githubusercontent.com/assets/10267317/14581217/7ba7724e-03ef-11e6-9f64-198eddda893d.png)

Thanks.

**Comment by petrsloup** [comment]
I've managed to reproduce this issue -- as far as I know, it only happens with certain datasets ("Turkey" and "Planet from z0 to z8 (411MB)") (from http://osm2vectortiles.org/downloads).

Requesting `/mapbox-studio-osm-bright/6/36/23.png` tile crashes the whole process.

**Comment by petrsloup** [comment]
XRay viewer works without any problems. Tile inspector reports:

```
tile: 6/23/36
PBF size: 215089 B (210 kB)
features: 5133
layers: 7

#landuse (features: 107)
    [osm_id]
    wood
        forest
        wood
    park
        national_park
        nature_reserve
#water (features: 285)
    [osm_id]
    no class
#road (features: 4573)
    [oneway]
    [osm_id]
    main
        trunk
    motorway
        motorway
#admin (features: 117)
    [admin_level]
    [disputed]
    [maritime]
    [osm_id]
    no class
#country_label (features: 13)
    [code]
    [name]
    [name_de]
    [name_en]
    [name_es]
    [name_fr]
    [name_ru]
    [name_zh]
    [osm_id]
    [scalerank]
    no class
#marine_label (features: 6)
    [labelrank]
    [name]
    [name_de]
    [name_en]
    [name_es]
    [name_fr]
    [name_ru]
    [name_zh]
    [osm_id]
    [placement]
    no class
#place_label (features: 32)
    [capital]
    [localrank]
    [name]
    [name_de]
    [name_en]
    [name_es]
    [name_fr]
    [name_ru]
    [name_zh]
    [osm_id]
    [scalerank]
    no class
```

**Comment by petrsloup** [comment]
This was an issue in the node-mapnik package: 3.5.2 works ok, 3.5.8 does not work, 3.5.11 works again.
This error was probably fixed in 3.5.10 (https://github.com/mapnik/node-mapnik/blob/master/CHANGELOG.md#3510) and we were probably just unlucky and picked up the broken version (although published as stable) during the automated build.

@webmap2015 Please download the latest version (`docker pull klokantech/tileserver-mapnik:latest`) and confirm this fixes your problem.

**Comment by hyperknot** [comment]
To avoid situations like this, maybe it would be good to pin known stable versions of Mapnik, so the docker container doesn't just use a random version of Mapnik (what is the whole point of Docker I'd guess).

Since it's a dependency of a dependency it might be tricky to pin it but I'm sure npm has tools for it. Actually it's a dependency of multiple dependencies (abaculus, tilelive-vector).

**Comment by klokan** [comment]
In this moment we have releases on github with configured autobuild on docker (such as https://github.com/klokantech/tileserver-mapnik/releases/tag/v2.0 and "v2.0" at https://hub.docker.com/r/klokantech/tileserver-mapnik/tags/) to preserve the tested version of tileserver-mapnik in the binary form including all dependencies in the moment of release - for easier production deployment and possibility to revert to an older version in case of issues with deployment of latest.

It is probably not ideal. We could declare explicit versions at npm requirements, but this means manual updates and testing of newly available dependencies on each release (or commit).
Ideal would be to combine this with CI tests (https://travis-ci.org/klokantech/tileserver-mapnik).
We run travis tests on https://github.com/klokantech/tileserver-gl

@hyperknot could you please make a related pull request for this particular case with mapnik version?

**Comment by webmap2015** [comment]
Thank you @petrsloup. Zoom level 6 is working without error.

**Comment by hyperknot** [comment]
@klokan @petrsloup I did a PR for this, it is a proper fix for the versions, but the Travis test is failing for some - I believe unrelated - reason can you have a look at the test?
https://github.com/klokantech/tileserver-mapnik/pull/17

**Comment by webmap2015** [comment]
Working good. Thanks.
