### ISSUE TITLE
Option to Output smaller and bigger tiles

### ISSUE THREAD

**Issue by g12n** [klokantech/tileserver-mapnik#16]
The minimum size of tiles is set to 256px. 

This can be cranked up to 512px using `@2x` and 768px using `@3x`

With a little bit of hacking I was able to extend with to `@4x`, `@5x` and so on. Making it suitable for large print outputs. 

Currently I am stuck on the opposite end of the food chain: To Create a **performant** user interface for large prints, with a decent level of realism, I need a output of the tiles **smaller** than 256px. The logical levels would be 128px and 64px. 

I tried changing [Line 150 in app.js](https://github.com/klokantech/tileserver-mapnik/blob/master/lib/app.js#L150)

Original: 

``` js
retinaURI.query.tileSize = scale * 256;
```

Changed value:

``` js
retinaURI.query.tileSize = scale * 128;
```

But this had – surprisingly – no effect at all. 

Can you guys point me into the right direction?

**Comment by klokan** [comment]
For print output there is the static maps API:

`/{basename}/static/{lon},{lat},{zoom}/{width}x{height}[@2x].{format}`

Where you can get output in pixels with specified width and height at given location and zoom.

**Comment by g12n** [comment]
Wow! Thank @klokan! This really amazing! 

Will solve a huge problem of ours!

Do you think, there is a way to solve out second problem? Serving vector-tiles in a smaller width. Imagine a hypothetical `@0.5x` resolution. Similar to a **thumbnail**.

Scaling them down inside the browser really messes up leaflet. And just showing a lower zoom level can be confusing, because some map features will look different on other levels.

**Comment by klokan** [comment]
I don't see any really practical use case for smaller tiles. There is no advantage it smaller tiles with @0.5x.

The thumbnail is required just one per map, no need for aligned tiles with other tiles in a smaller scale.
Either use a standard tile or construct static maps with pixel width+height + zoom + lat+lon request to get the image clipped the way you need it.

For a thumbnail with small, hardly readable, text just display the image in web browser smaller by CSS width and height override.

**Comment by g12n** [comment]
Thanks @klokan for your feedback. 

I see, that's not a feature, that would be widely used. So we would try to implement this in a custom version ourselves, Do you thinkt, there are fundametal obsticals that would prevent us from doing it? 

The smaller tiles are useful to create an interactive map where user can pick the location for a printed map. Of course Labels wont be readable on the preview. But using the the normal size would typically result in users picking a to hight zoom level for the map, where text labels will be to big. 

![map-preview](https://cloud.githubusercontent.com/assets/57556/14763581/a3a92f9e-0999-11e6-8c36-4e2b34b9b97b.jpg)
