### ISSUE TITLE
Static Maps URLs

### ISSUE THREAD

**Issue by klokan** [klokantech/tileserver-mapnik#2]
Add basic form of Static Maps API a la: https://www.mapbox.com/developers/api/static/

Could be powered by component: https://github.com/mapbox/abaculus

Similar implementation is already in:
https://github.com/kartotherian/kartotherian-server

**Comment by klokan** [comment]
This functionality is being also submitted via PR back to tessera master at:
https://github.com/mojodna/tessera/pull/31

**Comment by petrsloup** [comment]
PR merged, our fork rebased to have the updated version.
