### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by klokan** [klokantech/tileserver-mapnik#3]
Inspired by https://github.com/osm2vectortiles/osm2vectortiles/tree/master/src/serve but for our fork

**Comment by klokan** [comment]
Automated build configured: https://hub.docker.com/r/klokantech/tileserver-tessera/

@petrsloup has Admin access on Docker Hub.

**Comment by petrsloup** [comment]
Done. Automated builds are set up and working OK.
